# Render deployment configuration
services:
  - type: web
    name: tailortalk
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    buildCommand: ""
    startCommand: ""
    healthCheckPath: /_stcore/health
    envVars:
      - key: PORT
        value: 5000
      - key: STREAMLIT_SERVER_PORT
        value: 5000
      - key: STREAMLIT_SERVER_ADDRESS
        value: 0.0.0.0
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false